<?xml version="1.0" encoding="utf-8"?><Database Name="afdemp_csharp_1" Class="afdempDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-ATU40D6A\SQLEXPRESS;Initial Catalog=afdemp_csharp_1;Integrated Security=True" SettingsObjectName="Project_E_Banking.Properties.Settings" SettingsPropertyName="afdemp_csharp_1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.accounts" Member="accounts">
    <Type Name="account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="transaction_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="user_account" Member="user" ThisKey="user_id" OtherKey="id" Type="user" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="user_account" Member="accounts" ThisKey="id" OtherKey="user_id" Type="account" />
    </Type>
  </Table>
</Database>